### ISSUE TITLE
Source for Guido's quote about package managers

### ISSUE THREAD

**Issue by k-dominik** [ehansis/til#1]
Hi @ehansis,

in your Europython 2020 recap, you mention this very interesting quote (by Guido):

> "Only pip and conda will survive. Avoid pipenv or poetry, they aren't enough mainstream. The multiple config files will eventually converge."

is there a talk, or interview where this is coming from?

Cheers,

Dominik

**Comment by ehansis** [comment]
Hi Dominik,

this was from the conference chat on Discord, so there’s no recording (apart from the invite-only Discord server).

Cheers,
Eberhard

**Comment by k-dominik** [comment]
Hi Eberhard,

thanks for clearing that up. To bad I missed on on that :crying_cat_face: .
